// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#include "manager.h"


__attribute__((__import_module__("wasi:poll/poll"), __import_name__("drop-pollable")))
void __wasm_import_wasi_poll_poll_drop_pollable(int32_t);

__attribute__((__import_module__("wasi:poll/poll"), __import_name__("poll-oneoff")))
void __wasm_import_wasi_poll_poll_poll_oneoff(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("read")))
void __wasm_import_wasi_io_streams_read(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-read")))
void __wasm_import_wasi_io_streams_blocking_read(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("skip")))
void __wasm_import_wasi_io_streams_skip(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-skip")))
void __wasm_import_wasi_io_streams_blocking_skip(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("subscribe-to-input-stream")))
int32_t __wasm_import_wasi_io_streams_subscribe_to_input_stream(int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("drop-input-stream")))
void __wasm_import_wasi_io_streams_drop_input_stream(int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("write")))
void __wasm_import_wasi_io_streams_write(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-write")))
void __wasm_import_wasi_io_streams_blocking_write(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("write-zeroes")))
void __wasm_import_wasi_io_streams_write_zeroes(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-write-zeroes")))
void __wasm_import_wasi_io_streams_blocking_write_zeroes(int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("splice")))
void __wasm_import_wasi_io_streams_splice(int32_t, int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("blocking-splice")))
void __wasm_import_wasi_io_streams_blocking_splice(int32_t, int32_t, int64_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("forward")))
void __wasm_import_wasi_io_streams_forward(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("subscribe-to-output-stream")))
int32_t __wasm_import_wasi_io_streams_subscribe_to_output_stream(int32_t);

__attribute__((__import_module__("wasi:io/streams"), __import_name__("drop-output-stream")))
void __wasm_import_wasi_io_streams_drop_output_stream(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-fields")))
void __wasm_import_wasi_http_types_drop_fields(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("new-fields")))
int32_t __wasm_import_wasi_http_types_new_fields(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-get")))
void __wasm_import_wasi_http_types_fields_get(int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-set")))
void __wasm_import_wasi_http_types_fields_set(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-delete")))
void __wasm_import_wasi_http_types_fields_delete(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-append")))
void __wasm_import_wasi_http_types_fields_append(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-entries")))
void __wasm_import_wasi_http_types_fields_entries(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("fields-clone")))
int32_t __wasm_import_wasi_http_types_fields_clone(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("finish-incoming-stream")))
void __wasm_import_wasi_http_types_finish_incoming_stream(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("finish-outgoing-stream")))
void __wasm_import_wasi_http_types_finish_outgoing_stream(int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-incoming-request")))
void __wasm_import_wasi_http_types_drop_incoming_request(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-outgoing-request")))
void __wasm_import_wasi_http_types_drop_outgoing_request(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-method")))
void __wasm_import_wasi_http_types_incoming_request_method(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-path-with-query")))
void __wasm_import_wasi_http_types_incoming_request_path_with_query(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-scheme")))
void __wasm_import_wasi_http_types_incoming_request_scheme(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-authority")))
void __wasm_import_wasi_http_types_incoming_request_authority(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-headers")))
int32_t __wasm_import_wasi_http_types_incoming_request_headers(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-request-consume")))
void __wasm_import_wasi_http_types_incoming_request_consume(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("new-outgoing-request")))
int32_t __wasm_import_wasi_http_types_new_outgoing_request(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("outgoing-request-write")))
void __wasm_import_wasi_http_types_outgoing_request_write(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-response-outparam")))
void __wasm_import_wasi_http_types_drop_response_outparam(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("set-response-outparam")))
int32_t __wasm_import_wasi_http_types_set_response_outparam(int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-incoming-response")))
void __wasm_import_wasi_http_types_drop_incoming_response(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-outgoing-response")))
void __wasm_import_wasi_http_types_drop_outgoing_response(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-response-status")))
int32_t __wasm_import_wasi_http_types_incoming_response_status(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-response-headers")))
int32_t __wasm_import_wasi_http_types_incoming_response_headers(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("incoming-response-consume")))
void __wasm_import_wasi_http_types_incoming_response_consume(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("new-outgoing-response")))
int32_t __wasm_import_wasi_http_types_new_outgoing_response(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("outgoing-response-write")))
void __wasm_import_wasi_http_types_outgoing_response_write(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("drop-future-incoming-response")))
void __wasm_import_wasi_http_types_drop_future_incoming_response(int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("future-incoming-response-get")))
void __wasm_import_wasi_http_types_future_incoming_response_get(int32_t, int32_t);

__attribute__((__import_module__("wasi:http/types"), __import_name__("listen-to-future-incoming-response")))
int32_t __wasm_import_wasi_http_types_listen_to_future_incoming_response(int32_t);

__attribute__((__import_module__("wasi:http/outgoing-handler"), __import_name__("handle")))
int32_t __wasm_import_wasi_http_outgoing_handler_handle(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);

__attribute__((__import_module__("wasi:cli/environment"), __import_name__("get-environment")))
void __wasm_import_wasi_cli_environment_get_environment(int32_t);

__attribute__((__import_module__("wasi:cli/environment"), __import_name__("get-arguments")))
void __wasm_import_wasi_cli_environment_get_arguments(int32_t);

__attribute__((__import_module__("wasi:cli/environment"), __import_name__("initial-cwd")))
void __wasm_import_wasi_cli_environment_initial_cwd(int32_t);
__attribute__((__weak__, __export_name__("cabi_post_ilhan:golem-poll-manager/api#login")))
void __wasm_export_exports_ilhan_golem_poll_manager_api_login_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}
__attribute__((__weak__, __export_name__("cabi_post_ilhan:golem-poll-manager/api#verify")))
void __wasm_export_exports_ilhan_golem_poll_manager_api_verify_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}
__attribute__((__weak__, __export_name__("cabi_post_ilhan:golem-poll-manager/api#refresh")))
void __wasm_export_exports_ilhan_golem_poll_manager_api_refresh_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}
__attribute__((__weak__, __export_name__("cabi_post_ilhan:golem-poll-manager/api#logout")))
void __wasm_export_exports_ilhan_golem_poll_manager_api_logout_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void manager_list_wasi_poll_poll_pollable_free(manager_list_wasi_poll_poll_pollable_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void manager_list_bool_free(manager_list_bool_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void manager_list_u8_free(manager_list_u8_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void manager_tuple2_list_u8_wasi_io_streams_stream_status_free(manager_tuple2_list_u8_wasi_io_streams_stream_status_t *ptr) {
  manager_list_u8_free(&ptr->f0);
}

void manager_result_tuple2_list_u8_wasi_io_streams_stream_status_void_free(manager_result_tuple2_list_u8_wasi_io_streams_stream_status_void_t *ptr) {
  if (!ptr->is_err) {
    manager_tuple2_list_u8_wasi_io_streams_stream_status_free(&ptr->val.ok);
  }
}

void manager_tuple2_string_string_free(manager_tuple2_string_string_t *ptr) {
  manager_string_free(&ptr->f0);
  manager_string_free(&ptr->f1);
}

void manager_list_tuple2_string_string_free(manager_list_tuple2_string_string_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    manager_tuple2_string_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void manager_list_string_free(manager_list_string_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    manager_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void manager_option_string_free(manager_option_string_t *ptr) {
  if (ptr->is_some) {
    manager_string_free(&ptr->val);
  }
}

void wasi_http_types_method_free(wasi_http_types_method_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 9: {
      manager_string_free(&ptr->val.other);
      break;
    }
  }
}

void wasi_http_types_scheme_free(wasi_http_types_scheme_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 2: {
      manager_string_free(&ptr->val.other);
      break;
    }
  }
}

void wasi_http_types_error_free(wasi_http_types_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      manager_string_free(&ptr->val.invalid_url);
      break;
    }
    case 1: {
      manager_string_free(&ptr->val.timeout_error);
      break;
    }
    case 2: {
      manager_string_free(&ptr->val.protocol_error);
      break;
    }
    case 3: {
      manager_string_free(&ptr->val.unexpected_error);
      break;
    }
  }
}

void manager_list_list_u8_free(manager_list_list_u8_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    manager_list_u8_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void manager_tuple2_string_list_u8_free(manager_tuple2_string_list_u8_t *ptr) {
  manager_string_free(&ptr->f0);
  manager_list_u8_free(&ptr->f1);
}

void manager_list_tuple2_string_list_u8_free(manager_list_tuple2_string_list_u8_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    manager_tuple2_string_list_u8_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void manager_option_wasi_http_types_scheme_free(manager_option_wasi_http_types_scheme_t *ptr) {
  if (ptr->is_some) {
    wasi_http_types_scheme_free(&ptr->val);
  }
}

void manager_result_wasi_http_types_outgoing_response_wasi_http_types_error_free(manager_result_wasi_http_types_outgoing_response_wasi_http_types_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    wasi_http_types_error_free(&ptr->val.err);
  }
}

void manager_result_wasi_http_types_incoming_response_wasi_http_types_error_free(manager_result_wasi_http_types_incoming_response_wasi_http_types_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
    wasi_http_types_error_free(&ptr->val.err);
  }
}

void manager_option_result_wasi_http_types_incoming_response_wasi_http_types_error_free(manager_option_result_wasi_http_types_incoming_response_wasi_http_types_error_t *ptr) {
  if (ptr->is_some) {
    manager_result_wasi_http_types_incoming_response_wasi_http_types_error_free(&ptr->val);
  }
}

void manager_result_string_string_free(manager_result_string_string_t *ptr) {
  if (!ptr->is_err) {
    manager_string_free(&ptr->val.ok);
  } else {
    manager_string_free(&ptr->val.err);
  }
}

void manager_result_void_string_free(manager_result_void_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    manager_string_free(&ptr->val.err);
  }
}

void manager_string_set(manager_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void manager_string_dup(manager_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void manager_string_free(manager_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[12];

void wasi_poll_poll_drop_pollable(wasi_poll_poll_pollable_t this) {
  __wasm_import_wasi_poll_poll_drop_pollable((int32_t) (this));
}

void wasi_poll_poll_poll_oneoff(manager_list_wasi_poll_poll_pollable_t *in, manager_list_bool_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_poll_poll_poll_oneoff((int32_t) (*in).ptr, (int32_t) (*in).len, ptr);
  *ret = (manager_list_bool_t) { (bool*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_io_streams_read(wasi_io_streams_input_stream_t this, uint64_t len, manager_result_tuple2_list_u8_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_read((int32_t) (this), (int64_t) (len), ptr);
  manager_result_tuple2_list_u8_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_list_u8_wasi_io_streams_stream_status_t) {
        (manager_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        (int32_t) (*((uint8_t*) (ptr + 12))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_blocking_read(wasi_io_streams_input_stream_t this, uint64_t len, manager_result_tuple2_list_u8_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_read((int32_t) (this), (int64_t) (len), ptr);
  manager_result_tuple2_list_u8_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_list_u8_wasi_io_streams_stream_status_t) {
        (manager_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) },
        (int32_t) (*((uint8_t*) (ptr + 12))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_skip(wasi_io_streams_input_stream_t this, uint64_t len, manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_skip((int32_t) (this), (int64_t) (len), ptr);
  manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_u64_wasi_io_streams_stream_status_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_blocking_skip(wasi_io_streams_input_stream_t this, uint64_t len, manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_skip((int32_t) (this), (int64_t) (len), ptr);
  manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_u64_wasi_io_streams_stream_status_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

wasi_io_streams_pollable_t wasi_io_streams_subscribe_to_input_stream(wasi_io_streams_input_stream_t this) {
  int32_t ret = __wasm_import_wasi_io_streams_subscribe_to_input_stream((int32_t) (this));
  return (uint32_t) (ret);
}

void wasi_io_streams_drop_input_stream(wasi_io_streams_input_stream_t this) {
  __wasm_import_wasi_io_streams_drop_input_stream((int32_t) (this));
}

void wasi_io_streams_write(wasi_io_streams_output_stream_t this, manager_list_u8_t *buf, manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_write((int32_t) (this), (int32_t) (*buf).ptr, (int32_t) (*buf).len, ptr);
  manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_u64_wasi_io_streams_stream_status_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_blocking_write(wasi_io_streams_output_stream_t this, manager_list_u8_t *buf, manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_write((int32_t) (this), (int32_t) (*buf).ptr, (int32_t) (*buf).len, ptr);
  manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_u64_wasi_io_streams_stream_status_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_write_zeroes(wasi_io_streams_output_stream_t this, uint64_t len, manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_write_zeroes((int32_t) (this), (int64_t) (len), ptr);
  manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_u64_wasi_io_streams_stream_status_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_blocking_write_zeroes(wasi_io_streams_output_stream_t this, uint64_t len, manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_write_zeroes((int32_t) (this), (int64_t) (len), ptr);
  manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_u64_wasi_io_streams_stream_status_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_splice(wasi_io_streams_output_stream_t this, wasi_io_streams_input_stream_t src, uint64_t len, manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_splice((int32_t) (this), (int32_t) (src), (int64_t) (len), ptr);
  manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_u64_wasi_io_streams_stream_status_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_blocking_splice(wasi_io_streams_output_stream_t this, wasi_io_streams_input_stream_t src, uint64_t len, manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_blocking_splice((int32_t) (this), (int32_t) (src), (int64_t) (len), ptr);
  manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_u64_wasi_io_streams_stream_status_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_io_streams_forward(wasi_io_streams_output_stream_t this, wasi_io_streams_input_stream_t src, manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_io_streams_forward((int32_t) (this), (int32_t) (src), ptr);
  manager_result_tuple2_u64_wasi_io_streams_stream_status_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (manager_tuple2_u64_wasi_io_streams_stream_status_t) {
        (uint64_t) (*((int64_t*) (ptr + 8))),
        (int32_t) (*((uint8_t*) (ptr + 16))),
      };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

wasi_io_streams_pollable_t wasi_io_streams_subscribe_to_output_stream(wasi_io_streams_output_stream_t this) {
  int32_t ret = __wasm_import_wasi_io_streams_subscribe_to_output_stream((int32_t) (this));
  return (uint32_t) (ret);
}

void wasi_io_streams_drop_output_stream(wasi_io_streams_output_stream_t this) {
  __wasm_import_wasi_io_streams_drop_output_stream((int32_t) (this));
}

void wasi_http_types_drop_fields(wasi_http_types_fields_t fields) {
  __wasm_import_wasi_http_types_drop_fields((int32_t) (fields));
}

wasi_http_types_fields_t wasi_http_types_new_fields(manager_list_tuple2_string_string_t *entries) {
  int32_t ret = __wasm_import_wasi_http_types_new_fields((int32_t) (*entries).ptr, (int32_t) (*entries).len);
  return (uint32_t) (ret);
}

void wasi_http_types_fields_get(wasi_http_types_fields_t fields, manager_string_t *name, manager_list_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_fields_get((int32_t) (fields), (int32_t) (*name).ptr, (int32_t) (*name).len, ptr);
  *ret = (manager_list_list_u8_t) { (manager_list_u8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_http_types_fields_set(wasi_http_types_fields_t fields, manager_string_t *name, manager_list_list_u8_t *value) {
  __wasm_import_wasi_http_types_fields_set((int32_t) (fields), (int32_t) (*name).ptr, (int32_t) (*name).len, (int32_t) (*value).ptr, (int32_t) (*value).len);
}

void wasi_http_types_fields_delete(wasi_http_types_fields_t fields, manager_string_t *name) {
  __wasm_import_wasi_http_types_fields_delete((int32_t) (fields), (int32_t) (*name).ptr, (int32_t) (*name).len);
}

void wasi_http_types_fields_append(wasi_http_types_fields_t fields, manager_string_t *name, manager_list_u8_t *value) {
  __wasm_import_wasi_http_types_fields_append((int32_t) (fields), (int32_t) (*name).ptr, (int32_t) (*name).len, (int32_t) (*value).ptr, (int32_t) (*value).len);
}

void wasi_http_types_fields_entries(wasi_http_types_fields_t fields, manager_list_tuple2_string_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_fields_entries((int32_t) (fields), ptr);
  *ret = (manager_list_tuple2_string_list_u8_t) { (manager_tuple2_string_list_u8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

wasi_http_types_fields_t wasi_http_types_fields_clone(wasi_http_types_fields_t fields) {
  int32_t ret = __wasm_import_wasi_http_types_fields_clone((int32_t) (fields));
  return (uint32_t) (ret);
}

void wasi_http_types_finish_incoming_stream(wasi_http_types_incoming_stream_t s, manager_option_wasi_http_types_trailers_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_finish_incoming_stream((int32_t) (s), ptr);
  manager_option_wasi_http_types_trailers_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
  }
  *ret = option;
}

void wasi_http_types_finish_outgoing_stream(wasi_http_types_outgoing_stream_t s, manager_option_wasi_http_types_trailers_t *trailers) {
  int32_t option;
  int32_t option1;
  if ((*trailers).is_some) {
    const wasi_http_types_trailers_t *payload0 = &(*trailers).val;
    option = 1;
    option1 = (int32_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  __wasm_import_wasi_http_types_finish_outgoing_stream((int32_t) (s), option, option1);
}

void wasi_http_types_drop_incoming_request(wasi_http_types_incoming_request_t request) {
  __wasm_import_wasi_http_types_drop_incoming_request((int32_t) (request));
}

void wasi_http_types_drop_outgoing_request(wasi_http_types_outgoing_request_t request) {
  __wasm_import_wasi_http_types_drop_outgoing_request((int32_t) (request));
}

void wasi_http_types_incoming_request_method(wasi_http_types_incoming_request_t request, wasi_http_types_method_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_method((int32_t) (request), ptr);
  wasi_http_types_method_t variant;
  variant.tag = (int32_t) (*((uint8_t*) (ptr + 0)));
  switch ((int32_t) variant.tag) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    case 2: {
      break;
    }
    case 3: {
      break;
    }
    case 4: {
      break;
    }
    case 5: {
      break;
    }
    case 6: {
      break;
    }
    case 7: {
      break;
    }
    case 8: {
      break;
    }
    case 9: {
      variant.val.other = (manager_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = variant;
}

void wasi_http_types_incoming_request_path_with_query(wasi_http_types_incoming_request_t request, manager_option_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_path_with_query((int32_t) (request), ptr);
  manager_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (manager_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option;
}

void wasi_http_types_incoming_request_scheme(wasi_http_types_incoming_request_t request, manager_option_wasi_http_types_scheme_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_scheme((int32_t) (request), ptr);
  manager_option_wasi_http_types_scheme_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      wasi_http_types_scheme_t variant;
      variant.tag = (int32_t) (*((uint8_t*) (ptr + 4)));
      switch ((int32_t) variant.tag) {
        case 0: {
          break;
        }
        case 1: {
          break;
        }
        case 2: {
          variant.val.other = (manager_string_t) { (char*)(*((int32_t*) (ptr + 8))), (size_t)(*((int32_t*) (ptr + 12))) };
          break;
        }
      }
      
      option.val = variant;
      break;
    }
  }
  *ret = option;
}

void wasi_http_types_incoming_request_authority(wasi_http_types_incoming_request_t request, manager_option_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_authority((int32_t) (request), ptr);
  manager_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (manager_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option;
}

wasi_http_types_headers_t wasi_http_types_incoming_request_headers(wasi_http_types_incoming_request_t request) {
  int32_t ret = __wasm_import_wasi_http_types_incoming_request_headers((int32_t) (request));
  return (uint32_t) (ret);
}

void wasi_http_types_incoming_request_consume(wasi_http_types_incoming_request_t request, manager_result_wasi_http_types_incoming_stream_void_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_request_consume((int32_t) (request), ptr);
  manager_result_wasi_http_types_incoming_stream_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

wasi_http_types_outgoing_request_t wasi_http_types_new_outgoing_request(wasi_http_types_method_t *method, manager_option_string_t *path_with_query, manager_option_wasi_http_types_scheme_t *scheme, manager_option_string_t *authority, wasi_http_types_headers_t headers) {
  int32_t variant;
  int32_t variant9;
  int32_t variant10;
  switch ((int32_t) (*method).tag) {
    case 0: {
      variant = 0;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 2: {
      variant = 2;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 3: {
      variant = 3;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 4: {
      variant = 4;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 5: {
      variant = 5;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 6: {
      variant = 6;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 7: {
      variant = 7;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 8: {
      variant = 8;
      variant9 = 0;
      variant10 = 0;
      break;
    }
    case 9: {
      const manager_string_t *payload8 = &(*method).val.other;
      variant = 9;
      variant9 = (int32_t) (*payload8).ptr;
      variant10 = (int32_t) (*payload8).len;
      break;
    }
  }
  int32_t option;
  int32_t option13;
  int32_t option14;
  if ((*path_with_query).is_some) {
    const manager_string_t *payload12 = &(*path_with_query).val;
    option = 1;
    option13 = (int32_t) (*payload12).ptr;
    option14 = (int32_t) (*payload12).len;
  } else {
    option = 0;
    option13 = 0;
    option14 = 0;
  }
  int32_t option23;
  int32_t option24;
  int32_t option25;
  int32_t option26;
  if ((*scheme).is_some) {
    const wasi_http_types_scheme_t *payload16 = &(*scheme).val;
    int32_t variant20;
    int32_t variant21;
    int32_t variant22;
    switch ((int32_t) (*payload16).tag) {
      case 0: {
        variant20 = 0;
        variant21 = 0;
        variant22 = 0;
        break;
      }
      case 1: {
        variant20 = 1;
        variant21 = 0;
        variant22 = 0;
        break;
      }
      case 2: {
        const manager_string_t *payload19 = &(*payload16).val.other;
        variant20 = 2;
        variant21 = (int32_t) (*payload19).ptr;
        variant22 = (int32_t) (*payload19).len;
        break;
      }
    }
    option23 = 1;
    option24 = variant20;
    option25 = variant21;
    option26 = variant22;
  } else {
    option23 = 0;
    option24 = 0;
    option25 = 0;
    option26 = 0;
  }
  int32_t option29;
  int32_t option30;
  int32_t option31;
  if ((*authority).is_some) {
    const manager_string_t *payload28 = &(*authority).val;
    option29 = 1;
    option30 = (int32_t) (*payload28).ptr;
    option31 = (int32_t) (*payload28).len;
  } else {
    option29 = 0;
    option30 = 0;
    option31 = 0;
  }
  int32_t ret = __wasm_import_wasi_http_types_new_outgoing_request(variant, variant9, variant10, option, option13, option14, option23, option24, option25, option26, option29, option30, option31, (int32_t) (headers));
  return (uint32_t) (ret);
}

void wasi_http_types_outgoing_request_write(wasi_http_types_outgoing_request_t request, manager_result_wasi_http_types_outgoing_stream_void_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_outgoing_request_write((int32_t) (request), ptr);
  manager_result_wasi_http_types_outgoing_stream_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_http_types_drop_response_outparam(wasi_http_types_response_outparam_t response) {
  __wasm_import_wasi_http_types_drop_response_outparam((int32_t) (response));
}

void wasi_http_types_set_response_outparam(wasi_http_types_response_outparam_t param, manager_result_wasi_http_types_outgoing_response_wasi_http_types_error_t *response, manager_result_void_void_t *ret) {
  int32_t result;
  int32_t result7;
  int32_t result8;
  int32_t result9;
  if ((*response).is_err) {
    const wasi_http_types_error_t *payload0 = &(*response).val.err;int32_t variant;
    int32_t variant5;
    int32_t variant6;
    switch ((int32_t) (*payload0).tag) {
      case 0: {
        const manager_string_t *payload1 = &(*payload0).val.invalid_url;
        variant = 0;
        variant5 = (int32_t) (*payload1).ptr;
        variant6 = (int32_t) (*payload1).len;
        break;
      }
      case 1: {
        const manager_string_t *payload2 = &(*payload0).val.timeout_error;
        variant = 1;
        variant5 = (int32_t) (*payload2).ptr;
        variant6 = (int32_t) (*payload2).len;
        break;
      }
      case 2: {
        const manager_string_t *payload3 = &(*payload0).val.protocol_error;
        variant = 2;
        variant5 = (int32_t) (*payload3).ptr;
        variant6 = (int32_t) (*payload3).len;
        break;
      }
      case 3: {
        const manager_string_t *payload4 = &(*payload0).val.unexpected_error;
        variant = 3;
        variant5 = (int32_t) (*payload4).ptr;
        variant6 = (int32_t) (*payload4).len;
        break;
      }
    }
    result = 1;
    result7 = variant;
    result8 = variant5;
    result9 = variant6;
  } else {
    const wasi_http_types_outgoing_response_t *payload = &(*response).val.ok;result = 0;
    result7 = (int32_t) (*payload);
    result8 = 0;
    result9 = 0;
  }
  int32_t ret10 = __wasm_import_wasi_http_types_set_response_outparam((int32_t) (param), result, result7, result8, result9);
  manager_result_void_void_t result11;
  switch (ret10) {
    case 0: {
      result11.is_err = false;
      break;
    }
    case 1: {
      result11.is_err = true;
      break;
    }
  }
  *ret = result11;
}

void wasi_http_types_drop_incoming_response(wasi_http_types_incoming_response_t response) {
  __wasm_import_wasi_http_types_drop_incoming_response((int32_t) (response));
}

void wasi_http_types_drop_outgoing_response(wasi_http_types_outgoing_response_t response) {
  __wasm_import_wasi_http_types_drop_outgoing_response((int32_t) (response));
}

wasi_http_types_status_code_t wasi_http_types_incoming_response_status(wasi_http_types_incoming_response_t response) {
  int32_t ret = __wasm_import_wasi_http_types_incoming_response_status((int32_t) (response));
  return (uint16_t) (ret);
}

wasi_http_types_headers_t wasi_http_types_incoming_response_headers(wasi_http_types_incoming_response_t response) {
  int32_t ret = __wasm_import_wasi_http_types_incoming_response_headers((int32_t) (response));
  return (uint32_t) (ret);
}

void wasi_http_types_incoming_response_consume(wasi_http_types_incoming_response_t response, manager_result_wasi_http_types_incoming_stream_void_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_incoming_response_consume((int32_t) (response), ptr);
  manager_result_wasi_http_types_incoming_stream_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

wasi_http_types_outgoing_response_t wasi_http_types_new_outgoing_response(wasi_http_types_status_code_t status_code, wasi_http_types_headers_t headers) {
  int32_t ret = __wasm_import_wasi_http_types_new_outgoing_response((int32_t) (status_code), (int32_t) (headers));
  return (uint32_t) (ret);
}

void wasi_http_types_outgoing_response_write(wasi_http_types_outgoing_response_t response, manager_result_wasi_http_types_outgoing_stream_void_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_outgoing_response_write((int32_t) (response), ptr);
  manager_result_wasi_http_types_outgoing_stream_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

void wasi_http_types_drop_future_incoming_response(wasi_http_types_future_incoming_response_t f) {
  __wasm_import_wasi_http_types_drop_future_incoming_response((int32_t) (f));
}

void wasi_http_types_future_incoming_response_get(wasi_http_types_future_incoming_response_t f, manager_option_result_wasi_http_types_incoming_response_wasi_http_types_error_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[20];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_http_types_future_incoming_response_get((int32_t) (f), ptr);
  manager_option_result_wasi_http_types_incoming_response_wasi_http_types_error_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      manager_result_wasi_http_types_incoming_response_wasi_http_types_error_t result;
      switch ((int32_t) (*((uint8_t*) (ptr + 4)))) {
        case 0: {
          result.is_err = false;
          result.val.ok = (uint32_t) (*((int32_t*) (ptr + 8)));
          break;
        }
        case 1: {
          result.is_err = true;
          wasi_http_types_error_t variant;
          variant.tag = (int32_t) (*((uint8_t*) (ptr + 8)));
          switch ((int32_t) variant.tag) {
            case 0: {
              variant.val.invalid_url = (manager_string_t) { (char*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
              break;
            }
            case 1: {
              variant.val.timeout_error = (manager_string_t) { (char*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
              break;
            }
            case 2: {
              variant.val.protocol_error = (manager_string_t) { (char*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
              break;
            }
            case 3: {
              variant.val.unexpected_error = (manager_string_t) { (char*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
              break;
            }
          }
          
          result.val.err = variant;
          break;
        }
      }
      
      option.val = result;
      break;
    }
  }
  *ret = option;
}

wasi_http_types_pollable_t wasi_http_types_listen_to_future_incoming_response(wasi_http_types_future_incoming_response_t f) {
  int32_t ret = __wasm_import_wasi_http_types_listen_to_future_incoming_response((int32_t) (f));
  return (uint32_t) (ret);
}

wasi_http_outgoing_handler_future_incoming_response_t wasi_http_outgoing_handler_handle(wasi_http_outgoing_handler_outgoing_request_t request, manager_option_wasi_http_outgoing_handler_request_options_t *options) {
  int32_t option12;
  int32_t option13;
  int32_t option14;
  int32_t option15;
  int32_t option16;
  int32_t option17;
  int32_t option18;
  if ((*options).is_some) {
    const wasi_http_outgoing_handler_request_options_t *payload0 = &(*options).val;
    int32_t option;
    int32_t option3;
    if (((*payload0).connect_timeout_ms).is_some) {
      const uint32_t *payload2 = &((*payload0).connect_timeout_ms).val;
      option = 1;
      option3 = (int32_t) (*payload2);
    } else {
      option = 0;
      option3 = 0;
    }
    int32_t option6;
    int32_t option7;
    if (((*payload0).first_byte_timeout_ms).is_some) {
      const uint32_t *payload5 = &((*payload0).first_byte_timeout_ms).val;
      option6 = 1;
      option7 = (int32_t) (*payload5);
    } else {
      option6 = 0;
      option7 = 0;
    }
    int32_t option10;
    int32_t option11;
    if (((*payload0).between_bytes_timeout_ms).is_some) {
      const uint32_t *payload9 = &((*payload0).between_bytes_timeout_ms).val;
      option10 = 1;
      option11 = (int32_t) (*payload9);
    } else {
      option10 = 0;
      option11 = 0;
    }
    option12 = 1;
    option13 = option;
    option14 = option3;
    option15 = option6;
    option16 = option7;
    option17 = option10;
    option18 = option11;
  } else {
    option12 = 0;
    option13 = 0;
    option14 = 0;
    option15 = 0;
    option16 = 0;
    option17 = 0;
    option18 = 0;
  }
  int32_t ret = __wasm_import_wasi_http_outgoing_handler_handle((int32_t) (request), option12, option13, option14, option15, option16, option17, option18);
  return (uint32_t) (ret);
}

void wasi_cli_environment_get_environment(manager_list_tuple2_string_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_cli_environment_get_environment(ptr);
  *ret = (manager_list_tuple2_string_string_t) { (manager_tuple2_string_string_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_cli_environment_get_arguments(manager_list_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_cli_environment_get_arguments(ptr);
  *ret = (manager_list_string_t) { (manager_string_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_cli_environment_initial_cwd(manager_option_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_cli_environment_initial_cwd(ptr);
  manager_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (manager_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option;
}

__attribute__((__export_name__("ilhan:golem-poll-manager/api#login")))
int32_t __wasm_export_exports_ilhan_golem_poll_manager_api_login(int32_t arg, int32_t arg0) {
  manager_string_t arg1 = (manager_string_t) { (char*)(arg), (size_t)(arg0) };
  manager_result_string_string_t ret;
  exports_ilhan_golem_poll_manager_api_login(&arg1, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const manager_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload2).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload2).ptr;
  } else {
    const manager_string_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("ilhan:golem-poll-manager/api#verify")))
int32_t __wasm_export_exports_ilhan_golem_poll_manager_api_verify(int32_t arg, int32_t arg0) {
  manager_string_t arg1 = (manager_string_t) { (char*)(arg), (size_t)(arg0) };
  manager_result_string_string_t ret;
  exports_ilhan_golem_poll_manager_api_verify(&arg1, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const manager_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload2).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload2).ptr;
  } else {
    const manager_string_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("ilhan:golem-poll-manager/api#refresh")))
int32_t __wasm_export_exports_ilhan_golem_poll_manager_api_refresh(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2) {
  manager_string_t arg3 = (manager_string_t) { (char*)(arg), (size_t)(arg0) };
  manager_string_t arg4 = (manager_string_t) { (char*)(arg1), (size_t)(arg2) };
  manager_result_string_string_t ret;
  exports_ilhan_golem_poll_manager_api_refresh(&arg3, &arg4, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const manager_string_t *payload5 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload5).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload5).ptr;
  } else {
    const manager_string_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("ilhan:golem-poll-manager/api#logout")))
int32_t __wasm_export_exports_ilhan_golem_poll_manager_api_logout(int32_t arg, int32_t arg0) {
  manager_string_t arg1 = (manager_string_t) { (char*)(arg), (size_t)(arg0) };
  manager_result_void_string_t ret;
  exports_ilhan_golem_poll_manager_api_logout(&arg1, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const manager_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload2).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload2).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

__attribute__((__export_name__("ilhan:golem-poll-manager/api#validate")))
int32_t __wasm_export_exports_ilhan_golem_poll_manager_api_validate(int32_t arg, int32_t arg0) {
  manager_string_t arg1 = (manager_string_t) { (char*)(arg), (size_t)(arg0) };
  bool ret = exports_ilhan_golem_poll_manager_api_validate(&arg1);
  return ret;
}

extern void __component_type_object_force_link_manager(void);
void __component_type_object_force_link_manager_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_manager();
}
